### ISSUE TITLE
Adding John the Ripper demo in Webapplication_security directory

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [CompassSecurity/security_resources#7]
Hello contributors, I would like to add notes about John The Ripper in the repo, should I go and proceed?

Hi @emanuelduss, @strongX509, @ibuetler, @bcyrill  can you please give me heads up as approval?

Thank you.

**Comment by ibuetler** [comment]
What kind of notes? 
Regards
Ivan

**Comment by ShubhamJagtap2000** [comment]
Hello @ibuetler,

Thank you for the update. I wanted to add a similar file regarding "John" tool as that of the existing "hydra_demo" 
https://github.com/CompassSecurity/security_resources/blob/main/webapplication_security/hydra_demo.md

I wanted to know your take on this. Should I proceed?

**Comment by emanuelduss** [comment]
Hi

The hydra commands are commands we use in our courses. This command can be used in our training infrastructure to demonstrate hydra.

The repo is not intended to be a general collection of tools and how to use them. We use it as a link collection for our course participants. So I think it's not necessary to add examples for John the Ripper.

However, if you have a good resource on John the Ripper with some examples, we could add this link to the link list below John The Ripper (https://github.com/CompassSecurity/security_resources/blob/main/README.md?plain=1#L327).

Best,
Mänu

**Comment by ShubhamJagtap2000** [comment]
Hello @emanuelduss 

I saw the link, it is a good resource for John, I think no need to add extra resource. We are good with it.

Thank you.
